const { chromium }=require('C:/Users/xsy66/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');const path=require('node:path');
const out=path.join(__dirname,'verification');fs.mkdirSync(out,{recursive:true});process.env.TEMP=out;process.env.TMP=out;
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1240,height:920}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4174/prototypes/punch-test/index.html');await page.waitForFunction(()=>window.punchDemo?.getState().ready);
await page.locator('#debug').check();await page.locator('#attack').click();await page.waitForTimeout(800);let state=await page.evaluate(()=>punchDemo.getState());console.log('First attack',JSON.stringify(state));if(state.hits!==1)throw Error('Expected one hit');
await page.keyboard.press('j');await page.waitForTimeout(800);state=await page.evaluate(()=>punchDemo.getState());if(state.hits!==2)throw Error('Expected two hits from two attacks');
await page.locator('#reset').click();await page.keyboard.down('a');await page.waitForTimeout(700);await page.keyboard.up('a');await page.keyboard.down('d');await page.waitForTimeout(30);await page.keyboard.up('d');await page.keyboard.press('j');await page.waitForTimeout(800);state=await page.evaluate(()=>punchDemo.getState());if(state.hits!==0)throw Error('Out-of-range attack damaged target');
await page.locator('#reset').click();await page.locator('#speed').selectOption('0.25');await page.locator('#attack').click();await page.waitForFunction(()=>punchDemo.getState().frame===6);await page.keyboard.press('Escape');const before=await page.evaluate(()=>punchDemo.getState().frame);await page.waitForTimeout(150);if(before!==await page.evaluate(()=>punchDemo.getState().frame))throw Error('Pause failed');await page.screenshot({path:path.join(out,'punch-active.png')});if(errors.length)throw Error(errors.join('\n'));console.log('PASS: loading, in-range hit, one hit per swing, miss, pause, no browser errors');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
